# Generated by Django 5.1.7 on 2025-05-05 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег (км)')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='Состояние')),
                ('modification', models.CharField(blank=True, max_length=100, verbose_name='Модификация')),
                ('engine_volume', models.CharField(blank=True, max_length=50, verbose_name='Объём двигателя')),
                ('engine_type', models.CharField(blank=True, max_length=50, verbose_name='Тип двигателя')),
                ('transmission', models.CharField(blank=True, max_length=50, verbose_name='Коробка передач')),
                ('drive', models.CharField(blank=True, max_length=50, verbose_name='Привод')),
                ('equipment', models.CharField(blank=True, max_length=200, verbose_name='Комплектация')),
                ('body_type', models.CharField(blank=True, max_length=50, verbose_name='Тип кузова')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('steering_wheel', models.CharField(blank=True, max_length=50, verbose_name='Руль')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость (руб.)')),
                ('price_arenda_car', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость (руб/час.)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
